name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd src
          npm ci

      - name: Build and export static site
        run: |
          cd src
          npm run build
          npm run export

      - name: Upload static site
        uses: actions/upload-pages-artifact@v1
        with:
          path: src/out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1